# Generated by Django 4.2.1 on 2023-05-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='google_plus_link',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
